name: Daily Crypto Tracker

on:
  workflow_dispatch: # Manual trigger from GitHub
  schedule:
    - cron: "0 12 * * *" # Every day at 12:00 UTC

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tracker script
        env:
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
        run: |
          python main.py

      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add crypto_data.csv
          git commit -m "Update crypto tracker data [skip ci]" || echo "No changes to commit"
          git push

